### ISSUE TITLE
Using boto3 instead of secrets stored in SecretManager?

### ISSUE THREAD

**Issue by rantoniuk** [aws-hebrew-book/serverless-django#1]
> When migrating an application to the cloud, it presents an excellent opportunity to leverage other cloud services. In this example, we utilize AWS Secret Manager to store the database password and the Django secret key. To retrieve the secret values and integrate them into the Django app, we employ [Lambda Power Tools](https://awslabs.github.io/aws-lambda-powertools-python/2.12.0/utilities/parameters/#fetching-secrets) , simplifying the process of securely accessing these sensitive pieces of information.

I'm wondering, why did you prefer this solution instead of using [PGSQL IAM authentication using boto3](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Python.html)?

**Comment by having-fun-serverless** [comment]
Hey @rantoniuk , thank you for asking.  For no particular reason, your suggestion is just as good and for security reasons even better. Just make sure to account for the 200 connection per second limitation. 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html
